{ config, pkgs, ... }:

{
   home.packages = with pkgs; [
        adwaita-icon-theme
        anki
        bash-language-server
        bitwarden-desktop
        bottles
        btop
        calibre
        cava
        cliphist
        cloc
        cmake-language-server
        copilot-language-server
        cppcheck
        dnsutils
        docker-language-server
        dia
        discord
        electron
        ffmpeg
        file
        filezilla
        fzf
        gimp3-with-plugins
        gnupg
        gnused
        gnutar
        haskell-language-server
        hyprcursor
        hyprpaper
        hyprpicker
        hyprshot
        iftop
	    iotop
        jq
        lazygit
        librewolf
        lm_sensors
        lsof
        lua-language-server
        lutris
        ncdu
        neofetch
        nix-output-monitor
        nmap
        nvtopPackages.full
        nwg-displays
        mc
        mpv
        mpvScripts.mpris
        obs-studio
        obs-studio-plugins.obs-mute-filter
        obs-studio-plugins.obs-pipewire-audio-capture
        oh-my-zsh
        openmw
        openrgb-with-all-plugins
        openttd
        p7zip
        pciutils
        protonplus
        protonvpn-gui
        protonup-qt
        ripgrep
        rose-pine-hyprcursor
        signal-desktop
        sshfs
        slurp
        solaar
        spotify
        swappy
        texstudio
        tldr
        traceroute
        unzip
        usbutils
        vlc
        wget
        wine
        winetricks
        wireguard-tools
        which
        xz
        yaml-language-server
        yt-dlp
        zip
        zoom-us
        zsh-syntax-highlighting
    ];
}
