{ pkgs, inputs }:

{ config, pkgs, ... }:

{
    imports = [
        (import ./apps/hyprland.nix { inherit pkgs inputs; })
        ./apps/zsh.nix
        (import ./apps/neovim.nix { inherit pkgs inputs; })
        ./apps/games.nix
    ];

    home.packages = with pkgs; [
        anki
        kdePackages.audex
        btop
        bitwarden-desktop
        bottles
        btop
        calibre
        cava
        cloc
        cppcheck
        cuetools
        dnsutils
        dia
        discord
        easytag
        electron
        ffmpeg
        file
        filezilla
        flac
        flacon
        fzf
        freac
        gimp3-with-plugins
        git-crypt
        gnupg
        gnused
        gnutar
        gst_all_1.gstreamer
        gst_all_1.gst-plugins-base
        gst_all_1.gst-plugins-good
        gst_all_1.gst-plugins-ugly
        gst_all_1.gst-plugins-bad
        iftop
        image-roll
	    iotop
        jq
        lame
        lazygit
        libogg
        librewolf
        lm_sensors
        lsof
        mangohud
        ncdu
        neofetch
        nix-output-monitor
        nmap
        nvtopPackages.full
        nwg-displays
        mc
        mpv
        mpvScripts.mpris
        obs-studio
        obs-studio-plugins.obs-mute-filter
        obs-studio-plugins.obs-pipewire-audio-capture
        openrgb-with-all-plugins
        p7zip
        pciutils
        plexamp
        plex-desktop
        protonvpn-gui
        ripgrep
        shntool
        signal-desktop
        sshfs
        slurp
        solaar
        soundconverter
        sound-juicer
        spotify
        swappy
        texstudio
        tldr
        traceroute
        unzip
        usbutils
        vlc
        vorbis-tools
        wget
        wine
        winetricks
        wireguard-tools
        which
        xz
        yt-dlp
        zip
        zoom-us
    ];
}
